public class Deposit {
    /*
    - Masukkan jumlah uang yang ingin disetor namun harus dalam kelitapan 100.000 maksimal 10.000.000.
    - Jika dimasukkan uang yang bukan kelipatan 100.000 maka akan keluar informasi jumlah penyetoran harus kelipatan 100.000 dan tidak boleh melebihi 10.000.000.
    - Setelah berhasil menyetorkan uang maka saldo didalam rekening akan bertambah dan menghasilkan informasi Penyetoran berhasil.
    - Kemudian akan muncul berapa jumlah uang yang user miliki sekarang.*/
    }
}
